/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CollegeRankingSort =
  | "undergrad_tuition_in_state"
  | "name"
  | "median_sat"
  | "average_earnings"
  | "acceptance_rate"
  | "total_students"
  | "influence_score";

export interface CollegeRankingsRequest {
  sort: CollegeRankingSort;
  reversed: boolean;
  tuition: {
    min: number;
    max: number;
  };
  median_sat: {
    min: number;
    max: number;
  };
  acceptance_rate: {
    min: number;
    max: number;
  };
  total_students: {
    min: number;
    max: number;
  };
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CollegeRankingsResponse {
  schools: CollegeData[];
  limits: {
    tuition: {
      min: number;
      max: number;
    };
    median_sat: {
      min: number;
      max: number;
    };
    acceptance_rate: {
      min: number;
      max: number;
    };
    total_students: {
      min: number;
      max: number;
    };
  };
}
export interface CollegeData {
  id: string;
  name: string;
  city: string;
  state: string;
  median_act: number | null;
  median_sat: number | null;
  undergrad_tuition_in_state: number | null;
  average_earnings: number | null;
  total_students: number | null;
  influence_score: number | null;
  acceptance_rate: number | null;
  logo_url: string | null;
}
export const apiCollegeRankings = process.browser ? 
        async function(request: CollegeRankingsRequest): Promise<CollegeRankingsResponse> {
            const response = await fetch("/api/CollegeRankings/" + encodeURIComponent(JSON.stringify(request)));
            return response.json()
        } : async function(request: CollegeRankingsRequest): Promise<CollegeRankingsResponse> {
            const module = await import("./service/collegeRankings");
            return module.default(request)
        }
        